### ISSUE TITLE
error 404 for baseDicUrl in spell-checker.js

### ISSUE THREAD

**Issue by bazooka07** [inkdropapp/codemirror-spell-checker#3]
https://github.com/titoBouzout/Dictionaries/raw/master/ gives an 404 error.
The right link is 
https://raw.githubusercontent.com/titoBouzout/Dictionaries/master/
Take care of the name of language in this repository

There are more recent dictionaries at :
https://github.com/wooorm/dictionaries/tree/master/dictionaries

**Comment by craftzdog** [comment]
Thanks, I'll check it.
